    - name: Mettre à jour les paquets
      apt:
        update_cache: 'yes'
        upgrade: dist
    - name: Construire l'image Docker depuis le Dockerfile
      docker_image:
        build:
          path: ../DockerImages
        name: NodejsApp
        tag: latest
    - name: Lancer le conteneur Docker
      docker_container:
        name: mon_conteneur_node_js
        image: 'NodejsApp:latest'
        state: started
        restart_policy: always
        ports:
          - '3000:3000'
