- name: Remplacer l'IP dans inventory.ini
  run: >
    sed -i "s/{{ public_ip }}/${{ env.PUBLIC_IP }}/g"
    NodeJs_Service_Deployment/Ansible/inventory.ini
- name: config serveur
  hosts: web
  become: 'yes'
  roles:
    - role: base
      tags: base
    - role: git
      tags: git
    - role: app
      tags: app
    - role: nodejs
      tags: nodejs
    - role: ssh
      tags: ssh
