name: Deploy an App with docker-compose
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Ansible
        run: pip install ansible
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: >
          ansible-playbook -i Multi_Container_Application/Ansible/inventory.ini
          -u ubuntu --private-key ~/.ssh/id_ed25519
          Multi_Container_Application/Ansible/setup.yml
