- name: Mettre à jour les paquets
  apt:
    update_cache: 'yes'
    upgrade: dist
- name: Installer les utilitaires de base
  apt:
    name:
      - curl
      - vim
      - git
    state: present
- name: Installer fail2ban
  apt:
    name: fail2ban
    state: present
- name: S'assurer que fail2ban est démarré
  service:
    name: fail2ban
    state: started
    enabled: 'yes'
